# go-cqhttp config

account:
  uin: 2748080608
  encrypt: true
  status: 0
  relogin:
    disabled: true
    delay: 3
    interval: 0
    max-times: 0
  use-sso-address: true

heartbeat:
  disabled: false
  interval: 5

message:
  post-format: string
  ignore-invalid-cqcode: true
  force-fragment: false
  fix-url: false
  proxy-rewrite: ''
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false

output:
  log-level: warn
  debug: false

servers:
  - ws:
      disabled: false
      host: 127.0.0.1
      port: 6700
      middlewares:
        access-token: ''
        filter: ''
        rate-limit:
          enabled: false
          frequency: 1
          bucket: 1

database:
  leveldb:
    enable: true
